apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-test-config
  namespace: default
data:
  appsettings.json: "{
  \"Logging\": {
    \"IncludeScopes\": false,
    \"Debug\": {
      \"LogLevel\": {
        \"Default\": \"Warning\"
      }
    },
    \"Console\": {
      \"LogLevel\": {
        \"Default\": \"Warning\"
      }
    }
  },
  \"Services\": {
    \"Url\": \"http://hello:8080/hello\"
  }
}"